# Generated by Django 5.1.7 on 2025-04-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('accommodation_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_period', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='monthly', max_length=7)),
                ('number_of_beds', models.IntegerField()),
                ('number_of_bedrooms', models.IntegerField()),
                ('distance_from_campus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_status', models.BooleanField(default=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
