# Generated by Django 5.1.7 on 2025-04-02 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='accommodation_id',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
