# Generated by Django 5.1.7 on 2025-04-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodations', '0003_remove_accommodation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='name',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
