# Generated by Django 5.1.7 on 2025-04-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodations', '0004_alter_accommodation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='name',
        ),
    ]
