# Generated by Django 5.1.7 on 2025-04-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodations', '0005_remove_accommodation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='accommodation_id',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='name',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
