# Generated by Django 5.1.7 on 2025-04-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodations', '0006_remove_accommodation_accommodation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
