# Generated by Django 5.1.7 on 2025-04-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodations', '0007_accommodation_accommodation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='accommodation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
