# Generated by Django 5.1.7 on 2025-04-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodations', '0008_alter_accommodation_accommodation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='accommodation_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
