# Generated by Django 5.1.7 on 2025-04-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodations', '0011_remove_accommodation_distance_from_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
