# Generated by Django 5.1.7 on 2025-04-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodations', '0014_accommodation_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='university',
        ),
    ]
