# Generated by Django 5.1.7 on 2025-04-28 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_account', to='authtoken.token')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to='authentication.university')),
            ],
            options={
                'verbose_name': 'Service Account',
                'verbose_name_plural': 'Service Accounts',
            },
        ),
    ]
