# Generated by Django 5.1.7 on 2025-04-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='specialist_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
