# Generated by Django 5.1.7 on 2025-04-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_university_specialist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='specialist_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
