# Generated by Django 5.1.7 on 2025-04-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='created_time',
            new_name='updated_time',
        ),
    ]
