# Generated by Django 5.1.7 on 2025-06-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_rename_created_time_reservation_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('contract not signed', 'Contract Not Signed'), ('contract signed', 'Contract Signed'), ('cancelled', 'Cancelled')], default='Contract Not Signed', max_length=30),
        ),
    ]
